language: dart
sudo: required
dist: trusty
dart:
  - 2.1.0
  - stable
  - dev
before_script:
  - source $(pub run chrome_travis:env_rc)
script:
  - dart tool/travis.dart
matrix:
  allow_failures:
    - dart: dev