name: synchronized
description: Basic lock mechanism to prevent concurrent access to asynchronous code
version: 0.1.0
author: Alexandre Roux Tekartik <alex@tekartik.com>
homepage: https://github.com/tekartik/synchronized.dart

environment:
  sdk: '>=1.9.1 <2.0.0'

dependencies:
  func: any

dev_dependencies:
  test: '>=0.12.0'
  dev_test: '>=0.9.3'
  chrome_travis:
    git: git://github.com/tekartik/chrome_travis.dart
