name: synchronized
description: Lock mechanism to prevent concurrent access to asynchronous code
version: 1.5.3+2
author:  Tekartik <dev@tekartik.com>
homepage: https://github.com/tekartik/synchronized.dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: '>=0.12.0'
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
  build_runner: '>=0.9.2'
  build_test: '>=0.10.3'
