name: synchronized
description: Basic lock mechanism to prevent concurrent access to asynchronous code
version: 1.0.1
author:  Tekartik <dev@tekartik.com>
homepage: https://github.com/tekartik/synchronized.dart

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:

dev_dependencies:
  test: '>=0.12.0'
  dev_test: '>=0.9.3'
  browser: any
  chrome_travis:
    git: git://github.com/tekartik/chrome_travis.dart


# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
web:
  compiler:
    debug: dartdevc