name: synchronized
description: Lock mechanism to prevent concurrent access to asynchronous code
version: 1.5.1
author:  Tekartik <dev@tekartik.com>
homepage: https://github.com/tekartik/synchronized.dart

environment:
  sdk: '>=1.24.3 <3.0.0'

dev_dependencies:
  test: '>=0.12.0'
  dev_test: '>=0.9.3'
  browser: any
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
